# Generated by Django 2.0.4 on 2018-04-21 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
    ]
