# Generated by Django 2.0.4 on 2018-04-21 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20180421_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments_article',
            new_name='comment_article',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comments_text',
            new_name='comment_text',
        ),
    ]
